/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author vasco
 */
public class GUICheckin extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAddReserva
     */
    public GUICheckin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlCadastro = new javax.swing.JPanel();
        jblHospede = new javax.swing.JLabel();
        jblID = new javax.swing.JLabel();
        jblTelefone = new javax.swing.JLabel();
        jblEmail = new javax.swing.JLabel();
        jblCheckin = new javax.swing.JLabel();
        jblTipoQuarto = new javax.swing.JLabel();
        jchbxCadastroCasal = new javax.swing.JCheckBox();
        jchbxCadastroIndividual = new javax.swing.JCheckBox();
        jchbxCadastroFamilia = new javax.swing.JCheckBox();
        jblCheckout = new javax.swing.JLabel();
        jblPagamento = new javax.swing.JLabel();
        jchbxCredito = new javax.swing.JCheckBox();
        jchbxDebito = new javax.swing.JCheckBox();
        jchbxAvista = new javax.swing.JCheckBox();
        jbtnCadastrarHospede = new javax.swing.JButton();
        jbtnLimparCadastro = new javax.swing.JButton();
        jbtnVoltarCadastro = new javax.swing.JButton();
        jtfAddNome = new javax.swing.JTextField();
        jtfAddID = new javax.swing.JTextField();
        jtfAddEmail = new javax.swing.JTextField();
        jtfAddTelefone = new javax.swing.JTextField();
        jtfCheckout = new javax.swing.JTextField();
        jtfCheckin = new javax.swing.JTextField();
        jblCafe = new javax.swing.JLabel();
        jchbxCafeSim = new javax.swing.JCheckBox();
        jchbxCafeNao = new javax.swing.JCheckBox();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro de Reserva - Hotel Bruno Corrêa");
        setVisible(true);

        jpnlCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jpnlCadastro.setForeground(new java.awt.Color(0, 0, 0));

        jblHospede.setForeground(new java.awt.Color(0, 0, 0));
        jblHospede.setText("Nome do Hóspede:");

        jblID.setForeground(new java.awt.Color(0, 0, 0));
        jblID.setText("RG ou CPF:");

        jblTelefone.setForeground(new java.awt.Color(0, 0, 0));
        jblTelefone.setText("Telefone:");

        jblEmail.setForeground(new java.awt.Color(0, 0, 0));
        jblEmail.setText("E-mail: ");

        jblCheckin.setForeground(new java.awt.Color(0, 0, 0));
        jblCheckin.setText("Check - in:");

        jblTipoQuarto.setForeground(new java.awt.Color(0, 0, 0));
        jblTipoQuarto.setText("Tipo de Quarto:");

        jchbxCadastroCasal.setForeground(new java.awt.Color(0, 0, 0));
        jchbxCadastroCasal.setText("Casal");

        jchbxCadastroIndividual.setForeground(new java.awt.Color(0, 0, 0));
        jchbxCadastroIndividual.setText("Individual");

        jchbxCadastroFamilia.setForeground(new java.awt.Color(0, 0, 0));
        jchbxCadastroFamilia.setText("Família");

        jblCheckout.setForeground(new java.awt.Color(0, 0, 0));
        jblCheckout.setText("Check - out:");

        jblPagamento.setForeground(new java.awt.Color(0, 0, 0));
        jblPagamento.setText("Método de pagamento:");

        jchbxCredito.setForeground(new java.awt.Color(0, 0, 0));
        jchbxCredito.setText("Crédito");

        jchbxDebito.setForeground(new java.awt.Color(0, 0, 0));
        jchbxDebito.setText("Débito");

        jchbxAvista.setForeground(new java.awt.Color(0, 0, 0));
        jchbxAvista.setText("Á Vista");

        jbtnCadastrarHospede.setForeground(new java.awt.Color(0, 0, 0));
        jbtnCadastrarHospede.setText("Cadastrar");

        jbtnLimparCadastro.setForeground(new java.awt.Color(0, 0, 0));
        jbtnLimparCadastro.setText("Limpar");
        jbtnLimparCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparCadastroActionPerformed(evt);
            }
        });

        jbtnVoltarCadastro.setForeground(new java.awt.Color(0, 0, 0));
        jbtnVoltarCadastro.setText("Voltar");
        jbtnVoltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVoltarCadastroActionPerformed(evt);
            }
        });

        jtfAddEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAddEmailActionPerformed(evt);
            }
        });

        jtfCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCheckinActionPerformed(evt);
            }
        });

        jblCafe.setForeground(new java.awt.Color(0, 0, 0));
        jblCafe.setText("Café da Manhã:");

        jchbxCafeSim.setForeground(new java.awt.Color(0, 0, 0));
        jchbxCafeSim.setText("Sim");

        jchbxCafeNao.setForeground(new java.awt.Color(0, 0, 0));
        jchbxCafeNao.setText("Não");

        javax.swing.GroupLayout jpnlCadastroLayout = new javax.swing.GroupLayout(jpnlCadastro);
        jpnlCadastro.setLayout(jpnlCadastroLayout);
        jpnlCadastroLayout.setHorizontalGroup(
            jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlCadastroLayout.createSequentialGroup()
                        .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblTelefone)
                            .addComponent(jblID)
                            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                                .addComponent(jbtnVoltarCadastro)))
                        .addGap(127, 127, 127))
                    .addGroup(jpnlCadastroLayout.createSequentialGroup()
                        .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnlCadastroLayout.createSequentialGroup()
                                    .addComponent(jblCheckin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnlCadastroLayout.createSequentialGroup()
                                    .addComponent(jblHospede)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfAddID, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfAddNome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfAddTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnlCadastroLayout.createSequentialGroup()
                                    .addComponent(jblEmail)
                                    .addGap(72, 72, 72)
                                    .addComponent(jtfAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                    .addComponent(jblCheckout)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                            .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jchbxCadastroIndividual)
                                                .addComponent(jchbxCafeSim))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jchbxCafeNao)
                                                .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                                    .addComponent(jchbxCadastroCasal)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jchbxCadastroFamilia)))))))
                            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                        .addComponent(jbtnCadastrarHospede)
                                        .addGap(27, 27, 27)
                                        .addComponent(jbtnLimparCadastro))
                                    .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jblPagamento)
                                        .addGroup(jpnlCadastroLayout.createSequentialGroup()
                                            .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jblTipoQuarto)
                                                .addComponent(jblCafe))
                                            .addGap(61, 61, 61)
                                            .addComponent(jchbxDebito)
                                            .addGap(12, 12, 12)
                                            .addComponent(jchbxCredito))))
                                .addGap(18, 18, 18)
                                .addComponent(jchbxAvista)))
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
        jpnlCadastroLayout.setVerticalGroup(
            jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblHospede)
                    .addComponent(jtfAddNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblID)
                    .addComponent(jtfAddID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblTelefone)
                    .addComponent(jtfAddTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblEmail))
                .addGap(12, 12, 12)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCheckin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCheckout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchbxCadastroIndividual)
                    .addComponent(jchbxCadastroCasal)
                    .addComponent(jchbxCadastroFamilia)
                    .addComponent(jblTipoQuarto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchbxCafeSim)
                    .addComponent(jchbxCafeNao)
                    .addComponent(jblCafe))
                .addGap(10, 10, 10)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCadastroLayout.createSequentialGroup()
                        .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblPagamento)
                            .addComponent(jchbxDebito)
                            .addComponent(jchbxCredito)
                            .addComponent(jchbxAvista))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCadastroLayout.createSequentialGroup()
                        .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnCadastrarHospede)
                            .addComponent(jbtnLimparCadastro)
                            .addComponent(jbtnVoltarCadastro))
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jtfAddEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAddEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddEmailActionPerformed

    private void jtfCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCheckinActionPerformed

    private void jbtnVoltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVoltarCadastroActionPerformed
        GUIPrincipal pr = new GUIPrincipal();
        pr.chamarMenu();
    }//GEN-LAST:event_jbtnVoltarCadastroActionPerformed

    private void jbtnLimparCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparCadastroActionPerformed
        limpar();
    }//GEN-LAST:event_jbtnLimparCadastroActionPerformed
        public void limpar() {
        //jtfCodigoProd.setText(null);
        jtfAddNome.setText(null);
        jtfAddID.setText(null);
        jtfAddTelefone.setText(null);
        jtfAddEmail.setText(null);
        jtfCheckin.setText(null);
        jtfCheckout.setText(null);
        jchbxCadastroIndividual.setSelected(false);
        jchbxCadastroCasal.setSelected(false);
        jchbxCadastroFamilia.setSelected(false);
        jchbxCafeSim.setSelected(false);
        jchbxCafeNao.setSelected(false);
        jchbxDebito.setSelected(false);
        jchbxCredito.setSelected(false);
        jchbxAvista.setSelected(false);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblCafe;
    private javax.swing.JLabel jblCheckin;
    private javax.swing.JLabel jblCheckout;
    private javax.swing.JLabel jblEmail;
    private javax.swing.JLabel jblHospede;
    private javax.swing.JLabel jblID;
    private javax.swing.JLabel jblPagamento;
    private javax.swing.JLabel jblTelefone;
    private javax.swing.JLabel jblTipoQuarto;
    private javax.swing.JButton jbtnCadastrarHospede;
    private javax.swing.JButton jbtnLimparCadastro;
    private javax.swing.JButton jbtnVoltarCadastro;
    private javax.swing.JCheckBox jchbxAvista;
    private javax.swing.JCheckBox jchbxCadastroCasal;
    private javax.swing.JCheckBox jchbxCadastroFamilia;
    private javax.swing.JCheckBox jchbxCadastroIndividual;
    private javax.swing.JCheckBox jchbxCafeNao;
    private javax.swing.JCheckBox jchbxCafeSim;
    private javax.swing.JCheckBox jchbxCredito;
    private javax.swing.JCheckBox jchbxDebito;
    private javax.swing.JPanel jpnlCadastro;
    private javax.swing.JTextField jtfAddEmail;
    private javax.swing.JTextField jtfAddID;
    private javax.swing.JTextField jtfAddNome;
    private javax.swing.JTextField jtfAddTelefone;
    private javax.swing.JTextField jtfCheckin;
    private javax.swing.JTextField jtfCheckout;
    // End of variables declaration//GEN-END:variables
}
