/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author vasco
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener {

    private boolean flagPet = false;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplPrincipal = new javax.swing.JPanel();
        jbtnInfo = new javax.swing.JButton();
        jbtnContato = new javax.swing.JButton();
        jbtnPrecos = new javax.swing.JButton();
        jbtCheckout = new javax.swing.JButton();
        jbtnCheckIn = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jbtnInfo.setText("Info");
        jbtnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInfoActionPerformed(evt);
            }
        });

        jbtnContato.setText("Contato");
        jbtnContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContatoActionPerformed(evt);
            }
        });

        jbtnPrecos.setText("Preços");
        jbtnPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrecosActionPerformed(evt);
            }
        });

        jbtCheckout.setText("Checkout");
        jbtCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckoutActionPerformed(evt);
            }
        });

        jbtnCheckIn.setText("Checkin");
        jbtnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckInActionPerformed(evt);
            }
        });

        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplPrincipalLayout = new javax.swing.GroupLayout(jplPrincipal);
        jplPrincipal.setLayout(jplPrincipalLayout);
        jplPrincipalLayout.setHorizontalGroup(
            jplPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPrincipalLayout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addGroup(jplPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnPrecos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnContato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbtnInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jplPrincipalLayout.setVerticalGroup(
            jplPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jbtnCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCheckout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnEditar)
                .addGap(5, 5, 5)
                .addComponent(jbtnPrecos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnContato)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContatoActionPerformed
        JOptionPane.showMessageDialog(null, "-Hotel Bruno Corrêa-" + "\nE-mail: hotelbrunocorrea@email.com " + "\nTelefone: 5133042235");

    }//GEN-LAST:event_jbtnContatoActionPerformed

    private void jbtnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInfoActionPerformed
        JOptionPane.showMessageDialog(null, "-Hotel Bruno Corrêa-" + "\nInformações: " + "\nCheckout a partir do 12:00" + "\nCafé da Manhã a partir das 8:00");
    }//GEN-LAST:event_jbtnInfoActionPerformed

    private void jbtnPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrecosActionPerformed
        JOptionPane.showMessageDialog(null, "-Hotel Bruno Corrêa-" + "\nValores: " + "\nQuarto individual: R$75.00/dia" + "\nQuarto Casal: R$160.00/dia" + "\nQuarto Família: R$300.00/dia");
    }//GEN-LAST:event_jbtnPrecosActionPerformed

    private void jbtCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckoutActionPerformed
        chamarCheckout();
    }//GEN-LAST:event_jbtCheckoutActionPerformed

    private void jbtnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckInActionPerformed
        chamarCheckin();
    }//GEN-LAST:event_jbtnCheckInActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        chamarEditar();
    }//GEN-LAST:event_jbtnEditarActionPerformed
    
    
    public void chamarCheckout() {
        if (!flagPet) {
            GUICheckout co = new GUICheckout();
            jplPrincipal.add(co);
            co.setVisible(true);
            flagPet = true;
            co.addInternalFrameListener(this);
            
        }
    }

    public void chamarCheckin() {
        if (!flagPet) {
            GUICheckin ci = new GUICheckin();
            jplPrincipal.add(ci);
            ci.setVisible(true);
            flagPet = true;
            ci.addInternalFrameListener(this);
            

        }
    }
    
     public void chamarEditar(){
         if(!flagPet){ 
            GUIQuartos qu = new GUIQuartos();
            jplPrincipal.add(qu);
            qu.setVisible(true);
            flagPet = true;
            qu.addInternalFrameListener(this);
            
         }
     }
     
     public void chamarMenu(){
         if(!flagPet){ 
            GUIPrincipal pr = new GUIPrincipal();
            jplPrincipal.add(pr);
            pr.setVisible(true);
            flagPet = true;
           
         }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtCheckout;
    private javax.swing.JButton jbtnCheckIn;
    private javax.swing.JButton jbtnContato;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnInfo;
    private javax.swing.JButton jbtnPrecos;
    private javax.swing.JPanel jplPrincipal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
       
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
       if(e.getInternalFrame() instanceof GUICheckin){
             flagPet = false;
         } if(e.getInternalFrame() instanceof GUIQuartos){
             flagPet = false;
            } if(e.getInternalFrame() instanceof GUICheckout){
             flagPet = false;
    }
    }
    
    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
       
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
       
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
        
    }
}
