/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author vasco
 */
public class GUIQuartos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIQuartos
     */
    public GUIQuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlEditarQuarto = new javax.swing.JPanel();
        jlblAddRemover = new javax.swing.JLabel();
        jchbxAddCasal = new javax.swing.JCheckBox();
        jchbxAddIndividual = new javax.swing.JCheckBox();
        jchbxAddFamilia = new javax.swing.JCheckBox();
        jbtnEditarIncluir = new javax.swing.JButton();
        jbtnEditarRemover = new javax.swing.JButton();
        jbtnEditarVoltar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Editar Quarto - Hotel Bruno Corrêa");

        jpnlEditarQuarto.setBackground(new java.awt.Color(255, 255, 255));

        jlblAddRemover.setForeground(new java.awt.Color(0, 0, 0));
        jlblAddRemover.setText("Adicionar/Remover quarto tipo:");

        jchbxAddCasal.setForeground(new java.awt.Color(0, 0, 0));
        jchbxAddCasal.setText("Casal (1 Cama de Casal)");

        jchbxAddIndividual.setForeground(new java.awt.Color(0, 0, 0));
        jchbxAddIndividual.setText("Individual (1 Cama de solteiro)");

        jchbxAddFamilia.setForeground(new java.awt.Color(0, 0, 0));
        jchbxAddFamilia.setText("Familia (1 Cama de Casal/2 Camas de Solteiro/1 Sofá - Cama)");
        jchbxAddFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbxAddFamiliaActionPerformed(evt);
            }
        });

        jbtnEditarIncluir.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEditarIncluir.setText("Incluir");

        jbtnEditarRemover.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEditarRemover.setText("Remover");

        jbtnEditarVoltar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEditarVoltar.setText("Voltar");
        jbtnEditarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlEditarQuartoLayout = new javax.swing.GroupLayout(jpnlEditarQuarto);
        jpnlEditarQuarto.setLayout(jpnlEditarQuartoLayout);
        jpnlEditarQuartoLayout.setHorizontalGroup(
            jpnlEditarQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlEditarQuartoLayout.createSequentialGroup()
                .addGroup(jpnlEditarQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlEditarQuartoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpnlEditarQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblAddRemover, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchbxAddIndividual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchbxAddCasal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchbxAddFamilia, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jpnlEditarQuartoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jbtnEditarIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEditarRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEditarVoltar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpnlEditarQuartoLayout.setVerticalGroup(
            jpnlEditarQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlEditarQuartoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlblAddRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jchbxAddIndividual)
                .addGap(18, 18, 18)
                .addComponent(jchbxAddCasal)
                .addGap(18, 18, 18)
                .addComponent(jchbxAddFamilia)
                .addGap(36, 36, 36)
                .addGroup(jpnlEditarQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEditarIncluir)
                    .addComponent(jbtnEditarRemover)
                    .addComponent(jbtnEditarVoltar))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlEditarQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlEditarQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchbxAddFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbxAddFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbxAddFamiliaActionPerformed

    private void jbtnEditarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarVoltarActionPerformed
       GUIPrincipal pr = new GUIPrincipal();
        pr.chamarMenu();
    }//GEN-LAST:event_jbtnEditarVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEditarIncluir;
    private javax.swing.JButton jbtnEditarRemover;
    private javax.swing.JButton jbtnEditarVoltar;
    private javax.swing.JCheckBox jchbxAddCasal;
    private javax.swing.JCheckBox jchbxAddFamilia;
    private javax.swing.JCheckBox jchbxAddIndividual;
    private javax.swing.JLabel jlblAddRemover;
    private javax.swing.JPanel jpnlEditarQuarto;
    // End of variables declaration//GEN-END:variables
}
